EV-1119: Back-End Criação de Usuário
HenriqueSilvaWarren/Everest03.NET pull request #1
Opened 2023-01-03 18:15 UTC by HenriqueSilvaWarren

## Jira Tracking
[EV-1119](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-1119)

## Description
In this PR CRUD operations were created for Customer model

## Checklist

- [x] Todas as regras de negócio contidas no card foram aplicadas
- [x] Dados foram salvos em memória usando Lifetime Singleton

2023-01-04 13:19 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários e sugestões. Teu Repository e Service eu faço a review depois que tu fizer essas primeiras, pois, vão impactar na estrutura deles. Só me avisar dai que eu volto aqui.

Qualquer dúvida estou a disposição.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +
```suggestion
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +        public CustomersController(CustomersService service)
```suggestion
        private CustomersService _service;
        
        public CustomersController(CustomersService service)
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +        }
```suggestion
        {
            _service = service;
        }
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +        }
Você precisa fazer o tratamento de nulidade deste construtor. Para isso basta clicar  no service que você passa como parâmetro, utilizar o atalho "Ctrl" + "." e clicar em "Add null check".

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +            }
```suggestion
            {            
                _service.setCustomer(body);
                return new CreatedResult("Post", "Created customer successfully");
            }
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +            }
É interessante que se retorne ao usuário o ID do customer criado, visto que ele será necessário para o Update, Delete e GetById. No momento, sem este dado retornado, o usuário precisa fazer um GetAll, achar o customer que ele deseja e verificar seu ID, o que é muito trabalhoso.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +        [ProducesResponseType(StatusCodes.Status400BadRequest)]
Não colocaste nos demais métodos da controller, assim seria necessário padronizar, retirando daqui, ou colocando nos demais.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new OkResult();
O retorno mais adequado para o Delete é o 204 (NoContent), que indica que houve sucesso na solicitação não há conteúdo que precisa ser enviado na resposta.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +        }
Aqui você está fazendo apenas um método de GetAll, sendo necessário também um GetById para retornar um customer em específico. Ele terá uma resposta OK e um erro NotFound

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +            }
Aqui você precisa ter mais um catch, o NotFound é apenas se o ID não existe, caso email ou cpf já existam para outro ID você precisa apresentar um BadRequest.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +
```suggestion
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +
Acredito que não esteja sendo usado.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +        public long Id { get; private set; }
```suggestion
        public long Id { get; set; }
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +        }
Criar uma classe abstrata que será herdada pela customer. Vai te facilitar ao longo dos cards pois haverão outras entidades que utilizarão do ID.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Everest03.NET.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
```suggestion
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Everest03.NET.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
É necessário revisar todo o trabalho para colocar as nulidades e usings de forma explicita, o atalho "Ctrl" +"." também ajuda para isso. É interessante também após realizar todas as importações os usings com o atalho "Ctrl" + "R" + "G", que vai retirar as não usadas e colocar eles em ordem alfabética. Por fim o atalho "Ctrl" + "K" + "D" ajuda com as indentações.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Everest03.NET.csproj
> +    <PackageReference Include="FluentValidation" Version="11.4.0" />
```suggestion
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Everest03.NET.csproj
> +    <PackageReference Include="FluentValidation" Version="11.4.0" />
Acredito que não é necessário, apenas o FluentValidation.AspNetCore.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<CustomersValidator>();
```suggestion
builder.Services.AddControllers() ;

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddSingleton<ICustomersService, CustomersService>();
builder.Services.AddSingleton<ICustomersRepository, CustomersRepository>();
builder.Services.AddFluentValidationAutoValidation();
builder.Services.AddScoped<IValidator<Customers, CustomersValidator>();
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<CustomersValidator>();
Com o AddFluentValidationAutoValidation você já tem as configurações que precisa.

O AddScoped<IValidator<Customers, CustomersValidator>() permite que você não tenha que ficar informando em cada método que precisa usar o validador, ele automaticamente vai chamar toda vez que tiver uma entrada para o Customer.

Quanto as camadas Service e Repository, passar toda a lógica presente na Service para a Repository, a Service irá apenas chamar a Repository. Ainda, neste momento não é necessário ter as duas camadas (Service e Repository) apenas a Service é suficiente, mas se quiser manter sem problemas. Entretanto sua camada Service deve ser a AppService e a Repository passa a se chamar Service (mesmo que passa tudo para a atual Repository e mantenha apenas ela, deve renomear para Service). Também é importante criar as Interfaces de ambas, ou apenas da Service se manter só uma.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +    using FluentValidation;
```suggestion
using FluentValidation;

﻿namespace Everest03.NET.Validators
{
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +            RuleFor(customer => customer.EmailConfirmation).NotNull().EmailAddress().Equal(customer => customer.Email);
```suggestion
            RuleFor(customer => customer)
            .Must(customer => customer.EmailConfirmation == customer.Email);
```

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +            RuleFor(customer => customer.EmailConfirmation).NotNull().EmailAddress().Equal(customer => customer.Email);
Assim a gente determina que ele precisa ser igual ao Email e não precisamos fazer as verificações iguais ao do Email.

2023-01-04 13:19 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +        public CustomersValidator()
Te recomendo a usar NotEmpty() no lugar de NotNull(), porque o NotEmpty já garante que também não pode ser nulo. Além disso acredito que tu pode colocar mais validadores como verificar se o customer é maior de idade e determinar um tamanho mínimo para nome completo, país e endereço. Além disso é possível verificar se PostalCode e Cellphone estão em formatos válidos.

2023-01-05 12:05 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários. Qualquer dúvida estou a disposição.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +using Everest03.NET.Service;
```suggestion
using Everest03.NET.Service;
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        private Service.Service _repository;
```suggestion
        private Service _repository;
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        private Service.Service _repository;
Se precisar de importação deve estar nos usings antes do namespace, salvo casos muito específicos onde tu vai ter o using dentro da classe.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        public AppService(Service.Service repository, List<Customer> customers)
```suggestion

        public AppService(Service.Service repository, List<Customer> customers)
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +            _customers= customers;
```suggestion
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        public List<Customer> GetCustomers()
```suggestion
        }

        public List<Customer> GetCustomers()
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        public AppService(Service.Service repository, List<Customer> customers)
Não há a necessidade da manipulação da lista aqui no AppService. Neste momento ele vai servir apenas de camada intermediária para chamar o Service. Toda tua lógica e manipulação da lista, que é o teu "banco" neste caso irá ocorrer no Service.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +            return _repository.GetCustomerById(Id);
```suggestion
        {
            return _repository.GetCustomerById(Id);
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        }
```suggestion
        {
            _repository.DeleteCustomer(Id);
        }
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        }
```suggestion
        {
            customer.Cpf = new Regex("[.-]").Replace(customer.Cpf, string.Empty);
            _repository.SetCustomer(customer);
        }
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +        }
```suggestion
        {
            _repository.UpdateCustomer(Id, customer);
        }
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +
```suggestion
    }
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +
Passar tudo isso para o Service. Os três métodos podem ser private e não precisam estar na interface.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/IAppService.cs
> +        void CpfAlreadyExists(string cpf, long Id = 0);
```suggestion
        List<Customer> GetCustomers();
        Customer GetCustomerById(long Id);
        void DeleteCustomer(long Id);
        void SetCustomer(Customer customer);
        void UpdateCustomer(long Id, Customer customer);
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +            _repository = repository;
Fazer o tratamento para nulidade.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new CreatedResult("Post", $"Created customer successfully, ID: {body.Id}");
O ID não pode estar vindo do body, pode? Pois ele não é um dado de entrada que o usuário irá informar. O ID deve ser o retorno do método SetCustomer, já que apenas no Service o ID será determinado.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +    public class Customer : WithId
```suggestion
    public class Customer : ISetterId
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +    public class Customer : WithId
Acredito que o nome fica mais condizente já que é a Interface da Entidade.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +            ) {
```suggestion
            ) 
            {
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddAuthorization();
Para que esta sendo utilizado? Não é o mesmo da linha 40? Se for retirar daqui.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<AppService>();
```suggestion
builder.Services.AddSingleton<IAppService, AppService>();
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<AppService>();
Nas injeções de dependência sempre coloca a interface e a implementação dela, assim quando executado sempre que chamar essa interface o "programa" vai saber que tem que executar a implementação dela.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<List<Customer>>();
```suggestion
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<List<Customer>>();
Não tem necessidade, a lista de customers já faz parte do Service, e com a implementação dele já vais estar fazendo a da lista também.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<Service>();
```suggestion
builder.Services.AddSingleton<IService, Service>();   
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddSingleton<CustomersValidator>();
Acredito ser o mesmo que já consta na linha 25.
```suggestion
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +        private readonly List<Customer> _customers;
```suggestion
        private readonly List<Customer> _customers;
        
        public Service(List<Customer> customers) {
            _customers= customers;
        }
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +        private readonly List<Customer> _customers;
Sinceramente não sei se é um problema ou não, mas não me parece lógico fazer o construtor dizendo que  _customers= customers sem antes dizer o que é o _customers.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +            return _customers.FirstOrDefault(customer => customer.Id == Id)!;
Porque o operador ! no final?

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +    public class Service : IService
Não esqueça de trazer os 3 métodos que estavam no AppService para cá.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +    public class CustomersValidator : AbstractValidator<Customer>
```suggestion
namespace Everest03.NET.Validators
{
    public class CustomersValidator : AbstractValidator<Customer>
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +            RuleFor(customer => customer.Number).NotNull();
```suggestion
            RuleFor(customer => customer.FullName)
            .NotEmpty()
            .MinimumLength(8);
            
            RuleFor(customer => customer.Email)
            .NotEmpty()
            .EmailAddress();
            
            RuleFor(customer => customer)
            .Must(customer => customer.Email == customer.EmailConfirmation)
            .WithMessage("Email e EmailConfirmation precisam ser iguais");
            
            RuleFor(customer => customer.Cpf)
            .NotEmpty()
            .IsValidCPF();
            
            RuleFor(customer => customer.Cellphone)
            .NotEmpty()
            .Matches(@"\([0-9]{2}\)[0-9]{5}-[0-9]{4}");
            
            RuleFor(customer => customer.DateOfBirth)
            .NotEmpty()
            .LessThanOrEqualTo(DateTime.Now.AddYears(-18));
            
            RuleFor(customer => customer.EmailSms)
            .NotEmpty();
            
            RuleFor(customer => customer.Whatsapp)
            .NotEmpty();
            
            RuleFor(customer => customer.Country)
            .NotEmpty()
            .MinimumLength(4);
            
            RuleFor(customer => customer.City)
            .NotEmpty();
            
            RuleFor(customer => customer.PostalCode)
            .NotEmpty()
            .Matches(@"[0-9]{5}-[0-9]{3}");
            
            RuleFor(customer => customer.Address)
            .NotEmpty()
            .MinimumLength(10);
            
            RuleFor(customer => customer.Number)
            .NotEmpty();
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +            RuleFor(customer => customer.Number).NotNull();
Acredito ser interessante colocar um .WithMessage no Cellphone e no PostalCode para informar como seriam os formatos válidos caso o usuário erre.

Eu não utilizei a extensão Extensions.FluentValidation.Br então não sei, mas se o EmailAddress() e o IsValidCPF() não apresentaram mensagens de erro caso o usuário erre, também é importante informar com o .WithMessage qual seria o formato que passa.

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/WithId.cs
> +    public interface WithId
```suggestion
    public interface ISetterId
```

2023-01-05 12:05 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +        }
Cria uma classe de implementação para a interface ISetterId com esse método, dai tu não vai precisar colocar esse método em todos as tuas entidades. 

Acredito que talvez seja necessário fazer a injeção de dependência do ISetterId e SetterId na Program.

2023-01-05 12:08 UTC, HenriqueSilvaWarren commented on Everest03.NET/Validators/CustomersValidator.cs
> +            RuleFor(customer => customer.Number).NotNull();
EmailAddress é do próprio FluentValidation, mas é acho que não tem a formatação correta.

2023-01-05 14:20 UTC, JoaoArrudaWarren commented on Everest03.NET/Services/Service.cs
> +            return _customers.FirstOrDefault(customer => customer.Id == Id)!;
na verdade, não sei o que essa operação quer dizer. O que ela faz?

2023-01-05 14:28 UTC, JoaoArrudaWarren commented on Everest03.NET/AppServices/AppService.cs
> +            IdExists(Id);
Acredito que lógicas com a lista (e a própria lista) deveriam ficar no repository (service), somente. Assim, quando fores lançar alguma exceção, lance elas na camada mais interna, para assim, ir subindo na pilha de exceção.

2023-01-05 14:31 UTC, JoaoArrudaWarren commented on Everest03.NET/AppServices/AppService.cs
> +    public class AppService : IAppService
O card não pede esta divisão de AppServices e Services ainda. Mas, você está acessando diretamente sua lista em mais de um lugar, o que seria proporcional a modificar o banco em uma camada imprópria. Aconselho a deixar as modificações na lista e o acesso a mesma somente na Service.

2023-01-05 14:33 UTC, JoaoArrudaWarren reviewed
Deixei alguns comentários. Alguns podem ou não serem aplicados.

2023-01-05 16:47 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários. Fico a disposição.

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/IAppService.cs
> +    }
```suggestion
        void UpdateCustomer(long Id, Customer customer);
    }
```

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +                var customer = _service.SetCustomer(body);
Acredito que aqui tu não precise trazer todo o Customer como resposta do método, acho mais eficiente tu trazer direto o ID.

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Customer.cs
> +    }
```suggestion
        public int Number { get; set; }
    }
```

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +        public Service(List<Customer> customers)
```suggestion
        private readonly List<Customer> _customers;
        
        public Service(List<Customer> customers)
```

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +        }
Podes colocar todos esses métodos como private, não é de interesse que o usuário consiga fazer uso deles individualmente ou em outro local. Então é melhor deixar eles restritos a essa classe.

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +        }
Conforme dito na controller acredito ser mais interessante retornar o ID e não o customer como um todo. Verificar nos outros locais onde esse método é chamado ou se encontra para alterar seu retorno.

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/IService.cs
> +        void CpfAlreadyExists(string cpf, long Id = 0);
```suggestion
```

2023-01-05 16:47 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/IService.cs
> +        void CpfAlreadyExists(string cpf, long Id = 0);
Conforme comentário deixado no Service.

2023-01-05 17:01 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +            return _customers.FirstOrDefault(customer => customer.Id == Id)!;
@JoaoArrudaWarren o @HenriqueSilvaWarren me disse agora, é o mesmo que tem no Flutter, como ele ta usando o método IdExists, ele sabe que se cair no return é porque tem esse Customer, então não tem como retornar o nulo, dai aparece o aviso que pode ser nulo, mas não tem como ser, dai essa ! garante que não vai ser nulo.

2023-01-05 17:04 UTC, gregoryzimmerwarren approved these changes
Precisa só arrumar mais essas duas questões de formatação ali, mas já vou deixar aprovado.

2023-01-05 17:04 UTC, gregoryzimmerwarren commented on Everest03.NET/AppServices/AppService.cs
> +}
```suggestion
        }
    }
}
```

2023-01-05 17:04 UTC, gregoryzimmerwarren commented on Everest03.NET/Services/Service.cs
> +        public void DeleteCustomer(long id)
```suggestion
        }
        
        public void DeleteCustomer(long id)
```

2023-01-05 17:19 UTC, JoaoArrudaWarren commented on Everest03.NET/Services/Service.cs
> +            return _customers.FirstOrDefault(customer => customer.Id == Id)!;
ah, entendi. Boa.

2023-01-05 17:20 UTC, JoaoArrudaWarren approved these changes
tá aprovado, meu rei.

2023-01-06 00:39 UTC, viniciusoliveira-warren commented on Everest03.NET/AppServices/AppService.cs
> +    public class AppService : IAppService
Nome do serviço está muito genérico, isso é uma grande má prática quando o serviço não é genérico

Dessa forma especificamos para o que/quem serve o serviço
```suggestion
    public class CustomerAppService : ICustomerAppService
```

2023-01-06 00:40 UTC, viniciusoliveira-warren commented on Everest03.NET/Customer.cs
> +    {
Ajustar endentação da classe ctrl + k + d

2023-01-06 00:41 UTC, viniciusoliveira-warren commented on Everest03.NET/Everest03.NET.csproj
> +  </ItemGroup>
Se não está utilizando podemos deletar
```suggestion
  <ItemGroup>
    <PackageReference Include="Extensions.FluentValidation.Br" Version="1.0.2" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>
```

2023-01-06 00:42 UTC, viniciusoliveira-warren commented on Everest03.NET/Services/Service.cs
> +    public class Service : IService
[Mesma coisa](https://github.com/HenriqueSilvaWarren/Everest03.NET/pull/1#discussion_r1063007694)

2023-01-06 00:44 UTC, viniciusoliveira-warren commented on Everest03.NET/Services/Service.cs
> +            return _customers.FirstOrDefault(customer => customer.Id == Id)!;
Se nunca é nulo pode trocar para First ao invés de FirstOrDefault e remover o !

2023-01-06 00:45 UTC, ghost commented on Everest03.NET/Services/Service.cs
> +            throw new Exception($"O id {id} não foi encontrado");
```suggestion
            if (_customers.Any(x => x.Id == id)) return;
            
            throw new Exception($"O id {id} não foi encontrado");
```

2023-01-06 00:46 UTC, ghost commented on Everest03.NET/Services/Service.cs
> +        private void IdExists(long id)
```suggestion
        private void Exists(long id)
```

2023-01-06 00:48 UTC, viniciusoliveira-warren commented on Everest03.NET/Services/Service.cs
> +            }
Usar método Any para verificar se já existe

PS: Para melhorar sua lógica você poderia juntar as 2 condições em apenas 1 if mas sugiro seguir com o método Any que faz a mesma coisa que seu foreeach

2023-01-06 00:49 UTC, viniciusoliveira-warren commented on Everest03.NET/Services/Service.cs
> +            }
[Mesma coisa](https://github.com/HenriqueSilvaWarren/Everest03.NET/pull/1#discussion_r1063011514)

2023-01-06 00:51 UTC, viniciusoliveira-warren commented on Everest03.NET/Services/Service.cs
> +            _customers.RemoveAll(customer => customer.Id == id);
Existe a possibilidade de haver mais de 1 customer com o mesmo Id?

Se sim, código está com um buraco na segurança
Se não: 
```suggestion
            _customers.Remove(customer => customer.Id == id);
```

2023-01-06 00:58 UTC, viniciusoliveira-warren commented on Everest03.NET/Shared/SetterId.cs
> +        }
Entendi o que tentou fazer aqui mas na verdade acabou piorando porque trocou o set publico por um método o que é completamente desnecessário

2023-01-06 00:59 UTC, viniciusoliveira-warren commented on Everest03.NET/Validators/CustomersValidator.cs
> +                .WithMessage("Email inv�lido, formata��o correta �: xxxxx@xxxxx.xxx");
```suggestion
                .WithMessage("Email inv�lido, formato esperado: xxxxx@xxxxx.xxx");
```

2023-01-06 01:02 UTC, viniciusoliveira-warren commented on Everest03.NET/Validators/CustomersValidator.cs
> +                .WithMessage("CPF inv�lido, formata��o correta �: 000.000.000-00");
Não é boa prática backend esperar receber valor mascarado, deve aceitar mas não obrigar
```suggestion
                .WithMessage("CPF inv�lido, formato esperado: 000.000.000-00");
```

2023-01-06 01:03 UTC, viniciusoliveira-warren commented on Everest03.NET/Validators/CustomersValidator.cs
> +                .WithMessage("N�mero de Telefone inv�lido, formata��o correta: (00)00000-0000");
```suggestion
                .WithMessage("N�mero de celular inv�lido, formato esperado: (00)00000-0000");
```

2023-01-06 01:03 UTC, viniciusoliveira-warren commented on Everest03.NET/Validators/CustomersValidator.cs
> +                .WithMessage("CEP inv�lido, formata��o correta �: 00000-000");
```suggestion
                .WithMessage("CEP inv�lido, formato esperado: 00000-000");
```

2023-01-06 01:07 UTC, viniciusoliveira-warren commented on Everest03.NET/Shared/SetterId.cs
> +    public class SetterId : ISetterId
Pelo o que essa classe faz não vejo motivos para ter interface, caso queira continuar com ela recomendaria transformar em abstract.

2023-01-06 01:11 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new NotFoundObjectResult(e.Message);
```suggestion
                return NotFound(e.Message);
```

2023-01-06 01:11 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new OkObjectResult(_service.GetCustomerById(Id));
```suggestion
                return Ok(_service.GetCustomerById(Id));
```

2023-01-06 01:13 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new OkObjectResult($"Cliente com ID: {Id} atualizado com sucesso!");
Seguindo boas práticas REST basta retornar status code de sucesso
```suggestion
                return NoContent();
```

2023-01-06 01:13 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new BadRequestObjectResult(e.Message);
```suggestion
                return BadRequest(e.Message);
```

2023-01-06 01:13 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new NotFoundObjectResult(e.Message);
```suggestion
                return NotFound(e.Message);
```

2023-01-06 01:13 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new NoContentResult();
```suggestion
                return NoContent();
```

2023-01-06 01:13 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new NotFoundObjectResult(e.Message);
```suggestion
                return NotFound(e.Message);
```

2023-01-06 01:14 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +        public IActionResult Delete([FromQuery] long Id)
Query apenas para parâmetros opcionais 
```suggestion
        [HttpDelete("{id}", Name = "DeleteCustomer")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public IActionResult Delete(long Id)
```

2023-01-06 01:17 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +                return new CreatedResult("Post", $"Created customer successfully, ID: {Id}");
[Quase a mesma coisa](https://github.com/HenriqueSilvaWarren/Everest03.NET/pull/1#discussion_r1063020164) única diferença é que manteria o created apenas retornando o Id

Expor Id do banco também não é uma boa prática PRINCIPALMENTE se for para um sistema externo
```suggestion
                return Created("", Id);
```

2023-01-06 01:18 UTC, viniciusoliveira-warren commented on Everest03.NET/Controllers/CustomersController.cs
> +        }
Usar nome da prop, parâmetro de acordo com o tipo

2023-01-06 01:19 UTC, viniciusoliveira-warren commented on Everest03.NET/AppServices/AppService.cs
> +        public long SetCustomer(Customer customer)
Não estamos setando valor, termo correto aqui seria Add ao invés de Set pois estamos adicionando e não alterando algo

2023-01-06 12:09 UTC, HenriqueSilvaWarren commented on Everest03.NET/Everest03.NET.csproj
> +  </ItemGroup>
Eu vou remover os outros dois, mas eu estou usando o FluentValidations.Br

2023-01-09 21:57 UTC, viniciusoliveira-warren approved these changes

2023-01-10 00:27 UTC, merged