EV-1155: Aprofundamento C# e .NET CORE
HenriqueSilvaWarren/Everest03.NET pull request #2
Opened 2023-01-10 14:53 UTC by HenriqueSilvaWarren

### Jira Tracking 
[EV-1155](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-1155)

### Description
In this PR the solution was re-structured to four projects that communicate between each other and represent layers of onion architecture.

### Checklist
- [x] Validações devem pertencer a camada de aplicação;

- [x] Única responsabilidade da api é receber requisições, endereçar requisições a camada de aplicação e retornar status code/response de acordo com o retorno da camada de aplicação.

2023-01-10 16:32 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários e sugestões, qualquer dúvida estou a disposição.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +    <Nullable>enable</Nullable>
Fazer as importações e nulidades manualmente.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices/CustomerAppService.cs
> +using DomainServices.Services;
```suggestion
using DomainModels;
using DomainServices.Services;
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices/CustomerAppService.cs
> +using DomainServices.Services;
Cuidar com essas linhas em branco desnecessárias.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices/CustomerAppService.cs
> +namespace AppServices.AppServices
Acredito que seja mais interessante renomear a pasta para apenas Services.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices/CustomerAppService.cs
> +           return customer.Id;
```suggestion
          return  _service.AddCustomer(customer);
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices/CustomerAppService.cs
> +           return customer.Id;
O seu Id é o retorno que o próprio Service irá te trazer, então não precisa novamente pedir esse retorno aqui, retornar o próprio método do Service irá fazer isso.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/AppServices/ICustomerAppService.cs
> +namespace AppServices.AppServices
Acredito ser interessante criar uma pasta chamada Interfaces e transferir esse arquivo para lá. Irá te ajudar futuramente com os próximos cards.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomersValidator.cs
> +                .Matches(@"\([0-9]{2}\)[0-9]{5}-[0-9]{4}")
Será que faz sentido [0-9]{5} ? porque o primeiro dos 5 dígitos precisa, necessariamente ser 9 para ser um número de celular válido, não?

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomersValidator.cs
> +                .MinimumLength(10);
De acordo com o [buscador de cep dos Correios](https://buscacepinter.correios.com.br/app/endereco/index.php) existem diversas "Rua A" pelo Brasil, então acredito que o valor mínimo deva ser alterado.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomersValidator.cs
> +                .MinimumLength(4);
```suggestion
                .MinimumLength(3);
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomersValidator.cs
> +                .MinimumLength(4);
Caso contrário, Irã ficaria de fora.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on DomainModels/DomainModels.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on DomainModels/DomainModels.csproj
> +    <Nullable>enable</Nullable>
Fazer as importações e nulidades manualmente.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Everest03.NET/Controllers/CustomersController.cs
> +using DomainModels;
```suggestion
using AppServices.AppServices;
using DomainModels;
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +using AppServices.Validators;
Usa o atalho "Ctrl+R+G" que além de excluir os não utilizados ele vai colocar os usings em ordem alfabética. Recomendo usar em todos os arquivos.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/DomainServices.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/DomainServices.csproj
> +    <Nullable>enable</Nullable>
Fazer as importações e nulidades manualmente.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +        public long AddCustomer(Customer customer)
```suggestion
        private readonly List<Customer> _customers = new();
        
        public long AddCustomer(Customer customer)
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            return customer.Id;
```suggestion
            customer.Cpf = new Regex("[.-]").Replace(customer.Cpf, string.Empty);
            CpfAlreadyExists(customer.Cpf);
            EmailAlreadyExists(customer.Email);            
            
            customer.Id = _customers.Any() ? _customers.LastOrDefault().Id + 1 : 1;
            _customers.Add(customer);
            
            return customer.Id;
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            return customer.Id;
Só para talvez ficar mais claro, primeiro fez um tratamento no cpf e depois as buscas, seguiu determinando o Id e add e por fim o retorno. Me parece que deixa um pouco melhor de ler o código com essas separações.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            _customers[index] = customer;
```suggestion
            Exists(Id);
            EmailAlreadyExists(customer.Email, Id);
            CpfAlreadyExists(customer.Cpf, Id);
            
            customer.Id = Id;
            var index = _customers.FindIndex(customer => customer.Id == Id);
            
            _customers[index] = customer;
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            _customers[index] = customer;
Mesmo caso do Add.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            if (_customers.Any(customer => customer.Email == email && customer.Id != Id)) { throw new ArgumentException("Email já existe"); }
```suggestion
            if (_customers.Any(customer => customer.Email == email && customer.Id != Id))
               { throw new ArgumentException("Email já existe"); }
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            if (_customers.Any(customer => customer.Email == email && customer.Id != Id)) { throw new ArgumentException("Email já existe"); }
Acho que fica melhor deixar em duas linhas para não ficar algo tão longo.
Só verifica a indentação dai.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            if (_customers.Any(customer => customer.Cpf == cpf && customer.Id != Id)) { throw new ArgumentException("Cpf já existe"); }
```suggestion
            if (_customers.Any(customer => customer.Cpf == cpf && customer.Id != Id))
               { throw new ArgumentException("Cpf já existe"); }
```

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/CustomerService.cs
> +            if (_customers.Any(customer => customer.Cpf == cpf && customer.Id != Id)) { throw new ArgumentException("Cpf já existe"); }
Idem anterior.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/Services/ICustomerService.cs
> +namespace DomainServices.Services
Também acho interessante criar uma pasta de Interfaces aqui no DomainService.

2023-01-10 16:32 UTC, gregoryzimmerwarren commented on Services/DomainServices.csproj
> +
O nome do csproj está como DomainServices, mas ao menos aqui ao lado na estrutura organizacional está aparecendo como Services apenas, verificar se por acaso realmente está assim, e se tiver mudar para deixar como DomainServices.

![image](https://user-images.githubusercontent.com/113135420/211607740-4ea6b16c-0dd0-4156-9126-e7105aae8885.png)

2023-01-10 19:25 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários e sugestões.

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        }
```suggestion
            return _service.AddCustomer(customer);
        }
```

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomersValidator.cs
> +                .MinimumLength(8);
```suggestion
                .MinimumLength(6);
```

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on AppServices/Validators/CustomersValidator.cs
> +                .MinimumLength(8);
Pensei na possibilidade de alguém chamada Ana Sá

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +            { throw new ArgumentException("Email já existe"); }
```suggestion
             throw new ArgumentException("Email já existe");
```

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +            { throw new ArgumentException("Email já existe"); }
Não há necessidade de se colocar { } quando se tem apenas uma linha de execução dentro do if

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +            { throw new ArgumentException("Cpf já existe"); }
```suggestion
             throw new ArgumentException("Cpf já existe");
```

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +
```suggestion
```

2023-01-10 19:25 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +
```suggestion
```

2023-01-10 20:06 UTC, gregoryzimmerwarren approved these changes

2023-01-10 23:08 UTC, JoaoArrudaWarren approved these changes

2023-01-11 15:17 UTC, viniciusoliveira-warren approved these changes

2023-01-11 15:54 UTC, merged