EV-1158: Boas Práticas na construção de API
HenriqueSilvaWarren/Everest03.NET pull request #4
Opened 2023-01-12 12:45 UTC by HenriqueSilvaWarren

## Jira Tracking
[EV-1058](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-1158)

## Description
In this PR the entity stopped being exposed directly to the api and instead AutoMapper and Dtos were used to create customized data objects for the user.

## Checklist
- [x] Requests recebidas pelos endpoints da api devem ser mapeadas para entidades de domínio; Ex: GetCustomerByDocumentRequest
- [x] Antes das AppServices retornarem os dados para api devemos mapear a(s) entidade(s) de domínio para entidade(s) de response da api; Ex: CustomerResult
- [x] Todos os mapeamentos de entidade(s) devem serem feitas na camada de aplicação(Application)

2023-01-12 13:44 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários e sugestões. 

Qualquer dúvida estou a disposição.

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +    <PackageReference Include="AutoMapper" Version="12.0.0" />
```suggestion
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +    <PackageReference Include="AutoMapper" Version="12.0.0" />
Se eu não estou enganado não tem a necessidade deste se você utilizou o AutoMapper.Extensions.Microsoft.DependencyInjection

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Dtos/UpdateCustomerDto.cs
> +
```suggestion
}
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on DomainModels/Entities/Customer.cs
> +using System.Security.Cryptography.X509Certificates;
Qual a necessidade desde using?

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on Everest03.NET/Program.cs
> +builder.Services.AddScoped<IValidator<UpdateCustomerDto>, UpdateCustomersValidator>();
Tu podes fazer como o AutoMapper, utilizando o AddValidatorsFromAssembly(Assembly.Load(nameof(AppServices)));

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Validators/CreateCustomersValidator.cs
> +    public class CustomersValidator : AbstractValidator<CreateCustomerDto>
```suggestion
    public class CreateCustomersValidator : AbstractValidator<CreateCustomerDto>
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            return customer;
```suggestion
            var customers = _service.GetCustomers();
            
            return _mapper.Map<List<GetCustomerDto>>(customers);
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            return customer;
Acho mais interessante deixar de forma separada, para poder, caso necessário ter um melhor entendimento durante debug.

Além disso, tu pode fazer o mapeamento informando que é uma lista diretamente dentro do map, não precisa colocar o ToList() no fim.

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            return _mapper.Map<GetCustomerDto>(_service.GetCustomerById(Id));
```suggestion
            var customer = _service.GetCustomerById(Id);
            
            return _mapper.Map<GetCustomerDto>(customer);
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            return _mapper.Map<GetCustomerDto>(_service.GetCustomerById(Id));
Idem comentário anterior.

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public long AddCustomer(CreateCustomerDto customer)
```suggestion
        public long AddCustomer(CreateCustomerDto createCustomer)
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public long AddCustomer(CreateCustomerDto customer)
Assim fica mais claro durante o mapeamento.

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            return _service.AddCustomer(mappedCustomer);
```suggestion
            var mappedCustomer = _mapper.Map<Customer>(createCustomer);
            
            return _service.AddCustomer(mappedCustomer);
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public void UpdateCustomer(long Id, UpdateCustomerDto customer)
```suggestion
        public void UpdateCustomer(long Id, UpdateCustomerDto updateCustomer)
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            _service.UpdateCustomer(Id, _mapper.Map<Customer>(customer));
```suggestion
            var mappedCustomer = _mapper.Map<Customer>(updateCustomer);
            
            _service.UpdateCustomer(Id, mappedCustomer);
```

2023-01-12 13:44 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            _service.UpdateCustomer(Id, _mapper.Map<Customer>(customer));
Mesmo caso dos anteriores, separar para ficar melhor o entendimento durante debug.

2023-01-12 14:05 UTC, HenriqueSilvaWarren commented on DomainModels/Entities/Customer.cs
> +using System.Security.Cryptography.X509Certificates;
nem sei que que é isso

2023-01-13 11:54 UTC, LostBestFriend commented on AppServices/Dtos/CreateCustomerDto.cs
> +    public class CreateCustomerDto
O sufixo "DTO" não é necessário. Podes chamar somente de CreateCustomer.

2023-01-13 11:55 UTC, LostBestFriend commented on AppServices/Dtos/GetCustomerDto.cs
> +        public GetCustomerDto(
Mesmo que o comentário anterior.

2023-01-13 11:55 UTC, LostBestFriend commented on AppServices/Dtos/UpdateCustomerDto.cs
> +    public class UpdateCustomerDto
Mesmo que o comentário anterior.

2023-01-13 12:00 UTC, LostBestFriend reviewed
Deixei dois comentários, somente. Só questão de nomenclatura msm. Mas de resto, está aprovado.

2023-01-13 12:24 UTC, JoaoArrudaWarren approved these changes
Aprovado.

2023-01-13 12:57 UTC, viniciusoliveira-warren approved these changes

2023-01-13 12:58 UTC, merged